# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /portfolio
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jose Melendez
user_description: Hello, My name is Jose Melendez. I am currently working as a photographer and looking for a full-time position as an iOS developer. I have been developing iOS apps for a little over a year. I currently have two apps on the App Store with more on the way. I first began developing iOS apps on my own, after some time I felt it would be a good idea to further my knowledge to a professional level. So I decided to attend a coding bootcamp in Salt Lake City, Utah, called DevMountain. It was a 12 week fully immersive program, where I gained the necessary knowledge to build iOS apps. I continued my learning after the bootcamp, by watching  Stanford University’s “Developing iOS Apps with Swift” course. This course really reinforced my knowledge of Swift and also introduced me to many new concepts and ways of building iOS apps. With my experience and continued passion for learning more, I believe I would be a great asset to any team. 
user_title: iOS Developer
email: JoseM_Melendez@icloud.com
twitter_username: JMMX10y
github_username:  JoseMelendez-X

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
